[package]

name = "sysly"
version = "0.0.1"
authors = ["softprops <d.tangren@gmail.com>"]
description = "A modern syslog udp and unix domain socket appender."
documentation = "https://github.com/softprops/sysly#readme"
homepage = "https://github.com/softprops/sysly"
repository = "https://github.com/softprops/sysly"
keywords = ["log", "logging", "syslog", "unix"]
license = "MIT"

[dependencies]
time = "0.1.17"