[package]

name = "sysly"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]
description = "A modern multi-transport syslog appender."
documentation = "https://github.com/softprops/sysly#readme"
homepage = "https://github.com/softprops/sysly"
repository = "https://github.com/softprops/sysly"
keywords = ["log", "logging", "syslog", "unix"]
license = "MIT"

[dependencies]
unix_socket = "0.1.0"
time = "0.1.19"